name: Check Version Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest  # Runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Git version
        run: git --version

      - name: Check Node.js version
        run: node -v

      - name: Check NPM version
        run: npm -v

      - name: Check Python version
        run: python3 --version

      - name: Check Java version
        run: java -version
